= Python Text Basics =
:doctype: book
:author: Bharath Kumar S P
:email: bharath030195@gmail.com
:stem: latexmath
:toc:

== f-strings ==
Formatted string Literals (f-string literals) has been introduced in Python 3.6 which offers several benefits over the older `.format()` string method. We can also do some python operations inside the `{ }` braces.

[source,python]
----
name = 'Fred'
print('His name is {var}.'.format(var=name))
print(f'His name is {name}.')

#output - print doesn't show quotation whereas executing just name, returns 'Fred'
His name is Fred.
His name is Fred.

d = {'a':123,'b':456}
print(f"Address: {d['a']} Main Street") # make sure to use different quotation marks outside
Address: 123 Main Street
----

NOTE: While printing a string, `print()` doesn't print `\n` character, it inserts a new line. first_line gives 'fooaaaabar\nfooabar\nfoobar' whereas print(first_line) gives each word in a line.

*Rounding numbers:* +
To round the numbers to 2 decimal places:

[source,python]
----
r = 5.4356789834
print(f"The value is {r:.2f}")
#output: The value is 5.44
----

*Minimum Widths, Alignment and Padding:*

* To set the minimum spaces, use the braces and pass an integer `{n}`. When setting minimum field widths make sure to take the longest item of the column into account.
* To set the alignment, use the character < for left-align, ^ for center, > for right.
* To set padding, precede the alignment character with the padding character (- and . are common choices).

[source,python]
----
library = [('Author', 'Topic', 'Pages'), 
           ('Twain', 'Rafting', 601), 
           ('Feynman', 'Physics', 95), 
           ('Hamilton', 'Mythology', 144)]

for book in library:
    print(f'{book[0]} {book[1]} {book[2]}')

#output
Author Topic Pages
Twain Rafting 601
Feynman Physics 95
Hamilton Mythology 144

for book in library:
    print(f'{book[0]:.<{10}} {book[1]:.<{10}} {book[2]:.>{7}}')

Author.... Topic..... ..Pages
Twain..... Rafting... ....601
Feynman... Physics... .....95
Hamilton.. Mythology. ....144
----

*Date Formatting:*

For a list of directives, refer to https://strftime.org/[strftime, window=_blank]

[source,python]
----
from datetime import datetime
today = datetime(year=2023, month=10, day=27)

print(today)
2023-10-27 00:00:00

print(f'{today:%B %d, %Y}')
October 27, 2023
----

== Working with Text Files ==

*Opening a file:* 

To grab files from any location on your computer, simply pass in the entire file path. 

* For Windows we need to use double \ so python doesn't treat the second \ as an escape character, a file path is in the form: myfile = ope ("C:\\Users\\YourUserName\\Home\\Folder\\myfile.txt")

* For MacOS and Linux we use slashes in the opposite direction: myfile = open("/Users/YourUserName/Folder/myfile.txt")

[source,python]
----
my_file = open('C:\\Users\\bharath-asus\\Documents\\LEARNING\\nlp_course\\00-Python-Text-Basics\\test.txt')
----

`my_file` is now an open file object held in memory. We'll perform some reading and writing exercises, and then we have to close the file to free up memory. 

*Reading the file:*

On reading the file for the second time, we get empty string. This happens because the cursor will be at the beginning of the file before reading it, then the cursor moves to the end of the file after having read it. So there is nothing left to read. We can reset the "cursor" to the start of the file using the `seek()` method (Index 0 is before any letters):

[source,python]
----
my_file.read()
'Hello, this is a quick test file.\nThis is the second line of the file.\n'

my_file.read()
''

# Seek to the start of file (index 0)
my_file.seek(0)

my_file.read()
'Hello, this is a quick test file.\nThis is the second line of the file.\n'

content = my_file.read()
print(content)
Hello, this is a quick test file.
This is the second line of the file.

#always remember to close it
my_file.close()
----

`content` is now a variable with the text file content stored as one large string. Even after closing, the variable `my_file` points to the same file object but we cannot read the content unless we open it again. 

The `.read()` command is used for small files when we want to grab and save everything as a string. When the file size is large, we can read it line by line using the `.readlines()` method. Use caution with large files, since everything will be held in memory.

[source,python]
----
my_file = open('test.txt')
my_file.readlines()

['Hello, this is a quick test file.\n',
 'This is the second line of the file.\n']

my_file.readlines()
[]

my_file.close()
----

Returns a list with each element being each line of the file. The character `\n` is used to identify the end of each line.

*Writing to a file:*

By default, the `open()` function will only allow us to read the file. We need to pass the argument 'w' to write over the file. Passing 'w+' lets us read and write to the file. If the file does not exist, one will be created.

[source,python]
----
my_file = open('test.txt', 'w+')
my_file.read()
''
----

WARNING: Opening a file with 'w' or 'w+' *truncates the original*, meaning that anything that was in the original file *is deleted*!

[source,python]
----
my_file.write('This is a new first line')

# Returns the number of characters written
24

my_file.seek(0)
my_file.read()
'This is a new first line'

my_file.close()
----

*Appending to a file:*

Passing the argument 'a' opens the file and puts the pointer at the end, so anything written is appended. Passing 'a+' lets us read and write to a file. If the file does not exist, one will be created.

[source,python]
----
my_file = open('test.txt','a+')
my_file.write('\nThis line is being appended to test.txt')
my_file.write('\nAnd another line here.')

#output 23

my_file.seek(0)
print(my_file.read())

Hello, this is a quick test file.
This is the second line of the file.
This line is being appended to test.txt
And another line here.

my_file.close()
----

*Aliases and Context Managers:*

We can assign temporary variable names as aliases, and manage the opening and closing of files automatically using a context manager. The file is closed automatically after performing the specified block operation.

[source,python]
----
with open('test.txt','r') as txt:
    first_line = txt.readlines()[0]

#equivalent to
txt = open('test.txt','r')
first_line = txt.readlines()[0]
txt.close()

print(first_line)
Hello, this is a quick test file.
----

== Working with PDF Files ==

The PyPDF2 library won't be able to extract text from a scanned PDF image. It is made to extract plausible text from PDF files directly created from a word processor. First we open a pdf with binary read mode `rb`, then create a reader object for it. 

[source,python]
----
import PyPDF2
f = open('US_Declaration.pdf','rb')
pdf_reader = PyPDF2.PdfReader(f)

#get number of pages
len(pdf_reader.pages) #5

#extract text from page 1
page_one = pdf_reader.pages[0]
page_one_text = page_one.extract_text()
page_one_text

f.close()
----

To grab each page as an item in a list:

[source,python]
----
pdf_text = []  
f = open('US_Declaration.pdf','rb')
pdf_reader = PyPDF2.PdfReader(f)

for p in range(len(pdf_reader.pages)):
    page = pdf_reader.pages[p]
    pdf_text.append(page.extract_text())

f.close()
----

